name: image_gallery_saver
description: A new flutter plugin project for save image to gallery, iOS need to add the following keys to your Info.plist file, the key is called Privacy - Photo Library Additions Usage Description in the visual editor.
version: 0.1.0
author: quicey <quiceyxu@gmail.com>
homepage: https://github.com/hui-z/image_gallery_saver

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.example.imagegallerysaver
    pluginClass: ImageGallerySaverPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter

